---
title: "RMarkdown Introduction"
output:
  html_document:
---

# Introduction

### Overview

R Markdown provides an authoring framework for data science. You can use a single R Markdown file to both

-   save and execute code

-   generate high quality reports that can be shared with an audience

R Markdown documents are fully reproducible and support dozens of static and dynamic output formats.

### Installation

Like the rest of R, R Markdown is free and open source. You can install the R Markdown package from CRAN with:

```         
install.packages("rmarkdown")
```

### Get Started

The links to the left provide a quick tour of R Markdown. The links at the top provide examples of R Markdown documents, as well as an in depth discussion of various R Markdown topics.

You may also find the following resources helpful:

-   [The R Markdown Cheatsheet](https://github.com/rstudio/cheatsheets/raw/main/rmarkdown-2.0.pdf)

-   [The R Markdown Reference Guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)
